services:

  tor-client:
    build:
      context: ./services/tor-client
      dockerfile: Dockerfile
      # args:
    container_name: tor-client
    # environment:
    volumes:
      - ${TOR_DATA}:/var/lib/tor:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.2
        ipv6_address: fd12:3456:789a::2
    # ports:
    # depends_on:
    restart: always
    init: true
    user: ${UID}
    command: --HashedControlPassword ${TOR_CONTROL_HASHED_PASSWORD}

  tor-relay:
    build:
      context: ./services/tor-relay
      dockerfile: Dockerfile
      # args:
    container_name: tor-relay
    # environment:
    volumes:
      - ${TOR_DATA}:/var/lib/tor:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.3
        ipv6_address: fd12:3456:789a::3
    ports:
      - "9001:9001"
      - "9030:9030"
    # depends_on:
    restart: always
    init: true
    user: ${UID}
    command: --Address ${HOST_PUBLIC_IP}

  i2pd:
    build:
      context: ./services/i2pd
      dockerfile: Dockerfile
      # args:
    container_name: i2pd
    # environment:
    volumes:
      - ${I2P_DATA}:/var/lib/i2pd:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.4
        ipv6_address: fd12:3456:789a::4
    ports:
      - "17604:17604/tcp"
      - "17604:17604/udp"
    # depends_on:
    restart: always
    init: true
    user: ${UID}
    command: -host=${HOST_PUBLIC_IP}

  knots:
    build:
      context: ./services/knots
      dockerfile: Dockerfile
      # args:
    container_name: knots
    # environment:
    volumes:
      - ${KNOTS_DATA}:/var/lib/knots:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.5
        ipv6_address: fd12:3456:789a::5
    ports:
      - "8332:8332"
    depends_on:
      - tor-client
      - i2pd
    restart: always
    init: true
    user: ${UID}
    command: -rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD} -torpassword=${TOR_CONTROL_PASSWORD}

networks:
  nodenet:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.28.0.0/28
        - subnet: fd12:3456:789a::/124