services:

  tor:
    build:
      context: ./services/tor
      dockerfile: Dockerfile
      args:
        TOR_UID: ${TOR_UID}
        TOR_GID: ${TOR_GID}
    container_name: tor
    # environment:
    volumes:
      - ${TOR_DIR}:/var/lib/tor:rw
    # secrets:
    ports:
      - "9050:9050"
      - "9051:9051"
      - "9001:9001"
    networks:
      - bitcoin-net
    restart: always
    # depends_on:
    init: true

  knots:
    build:
      context: ./services/knots
      dockerfile: Dockerfile
      args:
        KNOTS_UID: ${KNOTS_UID}
        KNOTS_GID: ${KNOTS_GID}
        TOR_GID: ${TOR_GID}
    container_name: knots
    # environment:
    volumes:
      - ${KNOTS_DIR}:/var/lib/knots:rw
      - ${TOR_DIR}:/var/lib/tor:ro
    # ports:
    networks:
      - bitcoin-net
    restart: always
    depends_on:
      tor:
        condition: service_healthy
    init: true

  # mempool:
  #TODO mempool service

networks:
  bitcoin-net:
    driver: bridge