services:

#TODO Fix p2p onion address not accessible from outside (likely a tor on alpine issue)

  tor-client:
    build:
      context: ./services/tor-client
      dockerfile: Dockerfile
      # args:
    container_name: tor-client
    # environment:
    volumes:
      - tor-data:/var/lib/tor:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.2
    # ports:
    # depends_on:
    restart: always
    init: true
    user: 1000:1000
    command: --HashedControlPassword ${TOR_CONTROL_HASHED_PASSWORD}
    post_start:
      - command: chown -R 1000:1000 /var/lib/tor
        user: root

  tor-relay:
    build:
      context: ./services/tor-relay
      dockerfile: Dockerfile
      # args:
    container_name: tor-relay
    # environment:
    volumes:
      - tor-data:/var/lib/tor:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.3
    ports:
      - "9001:9001"
      - "9030:9030"
    # depends_on:
    restart: always
    init: true
    user: 1000:1000
    command: --Address ${HOST_PUBLIC_IP}
    post_start:
      - command: chown -R 1000:1000 /var/lib/tor
        user: root

  knots:
    build:
      context: ./services/knots
      dockerfile: Dockerfile
      # args:
    container_name: knots
    # environment:
    volumes:
      - knots-data:/var/lib/knots:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.4
    ports:
      - "8332:8332"
    depends_on:
      - tor-client
    restart: always
    init: true
    user: 1000:1000
    command: -rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD} -torpassword=${TOR_CONTROL_PASSWORD}
    post_start:
      - command: chown -R 1000:1000 /var/lib/knots
        user: root

networks:
  nodenet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/28

volumes:
  tor-data:
  knots-data:
    driver: local
    driver_opts:
      type: none
      device: ${KNOTS_DIR}
      o: bind