services:

  tor-client:
    build:
      context: ./services/tor-client
      dockerfile: Dockerfile
      args:
        TOR_UID: ${TOR_UID}
        TOR_GID: ${TOR_GID}
    container_name: tor-client
    # environment:
    volumes:
      - ${TOR_DIR}:/var/lib/tor:rw
    # secrets:
    ports:
      - "8333:8333"
    networks:
      nodenet:
        ipv4_address: 172.28.0.2
    restart: always
    # depends_on:
    init: true

  tor-relay:
    build:
      context: ./services/tor-relay
      dockerfile: Dockerfile
      args:
        TOR_UID: ${TOR_UID}
        TOR_GID: ${TOR_GID}
    container_name: tor-relay
    # environment:
    volumes:
      - ${TOR_DIR}:/var/lib/tor:rw
    # secrets:
    ports:
      - "9001:9001"
      - "9030:9030"
    networks:
      nodenet:
        ipv4_address: 172.28.0.3
    restart: always
    # depends_on:
    init: true

  knots:
    build:
      context: ./services/knots
      dockerfile: Dockerfile
      args:
        KNOTS_UID: ${KNOTS_UID}
        KNOTS_GID: ${KNOTS_GID}
        TOR_GID: ${TOR_GID}
    container_name: knots
    volumes:
      - ${KNOTS_DIR}:/var/lib/knots:rw
      - ${TOR_DIR}:/var/lib/tor:ro
    # secrets:
    ports:
      - "8332:8332"
    networks:
      nodenet:
        ipv4_address: 172.28.0.4
    restart: always
    depends_on:
      - tor-client
    init: true
    command: -rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}

  mempool:
    image: mempool/mempool:v1.0
    container_name: mempool
    environment:
      BITCOIN_NODE_HOST: 172.28.0.4
      BITCOIN_NODE_USER: ${RPC_USER}
      BITCOIN_NODE_PASS: ${RPC_PASSWORD}
    # volumes:
    # secrets:
    ports:
      - "80:80"
    networks:
      nodenet:
        ipv4_address: 172.28.0.5
    restart: always
    depends_on:
      - knots
    init: true

networks:
  nodenet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/28