services:

  tor:
    build:
      context: ./services/tor
      dockerfile: Dockerfile
      args:
        TOR_UID: ${TOR_UID}
        TOR_GID: ${TOR_GID}
    container_name: tor
    # environment:
    volumes:
      - ${TOR_DIR}:/var/lib/tor:rw
    # secrets:
    ports:
      - "8333:8333"
    networks:
      - bitcoin-net
    restart: always
    # depends_on:
    init: true

  knots:
    build:
      context: ./services/knots
      dockerfile: Dockerfile
      args:
        KNOTS_UID: ${KNOTS_UID}
        KNOTS_GID: ${KNOTS_GID}
        TOR_GID: ${TOR_GID}
    container_name: knots
    # environment:
    volumes:
      - ${KNOTS_DIR}:/var/lib/knots:rw
      - ${TOR_DIR}:/var/lib/tor:ro
    # secrets:
    ports:
      - "8332:8332"
    networks:
      - bitcoin-net
    restart: always
    # depends_on:
    init: true

  # mempool:
  #TODO mempool service

networks:
  bitcoin-net:
    driver: bridge