services:

#TODO Fix p2p onion address not accessible from outside (likely a tor on alpine issue)

  tor-client:
    build:
      context: ./services/tor-client
      dockerfile: Dockerfile
      # args:
    container_name: tor-client
    # environment:
    volumes:
      - ${TOR_DATA}:/var/lib/tor:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.2
    # ports:
    # depends_on:
    restart: always
    init: true
    user: ${UID}
    command: --HashedControlPassword ${TOR_CONTROL_HASHED_PASSWORD}

  tor-relay:
    build:
      context: ./services/tor-relay
      dockerfile: Dockerfile
      # args:
    container_name: tor-relay
    # environment:
    volumes:
      - ${TOR_DATA}:/var/lib/tor:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.3
    ports:
      - "9001:9001"
      - "9030:9030"
    # depends_on:
    restart: always
    init: true
    user: ${UID}
    command: --Address ${HOST_PUBLIC_IP}

  knots:
    build:
      context: ./services/knots
      dockerfile: Dockerfile
      # args:
    container_name: knots
    # environment:
    volumes:
      - ${KNOTS_DATA}:/var/lib/knots:rw
    # secrets:
    networks:
      nodenet:
        ipv4_address: 172.28.0.4
    ports:
      - "8332:8332"
    depends_on:
      - tor-client
    restart: always
    init: true
    user: ${UID}
    command: -rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD} -torpassword=${TOR_CONTROL_PASSWORD}

networks:
  nodenet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/28